configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/xtrace/xtrace-memory-manager-cafbdfafdca9dfe3ab085be2c85eb312f92bf5dbd82cff67df5e4a478a3605c1.yml
openapi_spec_hash: f5b0148c800f181ccee41a1195070c8b
config_hash: 4df48d8c3e8146c08bfaff39226b4de7
